---
title: "Heart Disease"
author: "Author"
date: "2023-02-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tibble)
library(readr)
library(dplyr)

library(broom)
library(cowplot)

library(ggplot2)
#library(ggbiplot)
library(fastDummies)

#library(plotly)

```


Read data

```
63.0 male angina 145.0 233.0 true  hyp 150.0 fal  2.3 down 0.0  fix buff  H
67.0 male asympt 160.0 286.0 fal   hyp 108.0 true 1.5 flat 3.0 norm sick S2
67.0 male asympt 120.0 229.0 fal   hyp 129.0 true 2.6 flat 2.0  rev sick S1
37.0 male notang 130.0 250.0 fal  norm 187.0 fal  3.5 down 0.0 norm buff  H
41.0  fem abnang 130.0 204.0 fal   hyp 172.0 fal  1.4   up 0.0 norm buff  H
```

```{r}
# full is 303 -> 296 (removed missing)
df <- readr::read_table(
  file="heart_disease_cleve_mod.dat", comment = "%", 
  col_names = c(
    "age","sex","chest pain type", "trestbps", "cholesteral",
    "fasting blood sugar", "resting ecg", "max heart rate",
    "exercise induced angina", "oldpeak", "slope",
    "number of vessels colored", "thal", "class1", "class"
  ),
  na = "?") %>% 
  na.omit() %>%
  mutate(
    sick=as.integer(class1=="sick"),
    female=as.integer(sex=="fem"),
    `fasting blood sugar`=as.integer(`fasting blood sugar`=="true"),
    `exercise induced angina`=as.integer(`exercise induced angina`=="true"),
    slope=recode(slope, down=-1,flat=0,up=1),
    `resting ecg`=recode(`resting ecg`,`norm`=0, abn=1, hyp=2)
  ) %>%
  select(-sex,-class1) %>%
  fastDummies::dummy_cols(select_columns = "chest pain type",
                          remove_selected_columns = T) %>%
  fastDummies::dummy_cols(select_columns = "thal",
                          remove_selected_columns = T) %>%
  select(
    -`chest pain type_asympt`,
    -`thal_norm`
  ) %>%
  select(
    "sick", "class", everything()
  )
df
```

```{r}
save(df, file="heart_disease.Rdata")
```


```{r}
load(file="heart_disease.Rdata")
```


```{r}
pca_fit <- prcomp(df[c(-1,-2)], scale=T)
pca_fit
```

```{r}
pca_fit$sdev

```

```{r fig.width=5, fig.height=5}
ggbiplot(pca_fit,scale=0,groups = as.factor(df$class))
# %>% ggplotly()
#ggsave("biplot.svg")
```


```{r}
PVE <- tibble(
  PC=1:length(pca_fit$sdev),
  Var=pca_fit$sdev^2,
  PVE=Var/sum(Var),
  CumPVE=cumsum(PVE)
)
PVE
```


```{r fig.width=4,fig.height=2}
cowplot::plot_grid(
qplot(data=PVE,x=PC,y=PVE,geom=c("point","line"),
      xlab = "Principal Component",
      ylab = "Proportion of Variance Explained"),
qplot(data=PVE,x=PC,y=CumPVE,geom=c("point","line"),
      xlab = "Principal Component",
      ylab = "Cumulative Proportion of Variance Explained")
)

```

```{r fig.width=4,fig.height=3}
p <- ggplot(data=PVE,aes(x=PC))+
  geom_point(mapping = aes(y=PVE,color="Proportion of Variance Explained"))+
  geom_line(mapping = aes(y=PVE,color="Proportion of Variance Explained"))+
  geom_point(mapping = aes(y=CumPVE,color="Cumulative Proportion of Variance Explained"))+
  geom_line(mapping = aes(y=CumPVE,color="Cumulative Proportion of Variance Explained")) +
  theme(legend.position="bottom",legend.title = element_blank())+
  guides(col = guide_legend(ncol = 1))
p
```

```{r fig.width=4,fig.height=3}
p %>% ggplotly()
```



